# Development environment values

global:
  projectId: "gcp-poc-496714"
  region: "us-central1"
  zone: "us-central1-a"

app:
  replicaCount: 1
  properties:
    logLevel: "DEBUG"
    logLevelApp: "DEBUG"

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"

service:
  type: ClusterIP

autoscaling:
  enabled: false

healthChecks:
  liveness:
    enabled: true
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  readiness:
    enabled: true
    initialDelaySeconds: 50
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3

image:
  tag: "latest"
  pullPolicy: Always
