apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-gke-config
  namespace: dev
data:
  application.properties: |
    spring.application.name=hello-gke
    server.port=8080
    server.servlet.context-path=/
    logging.level.root=INFO
    logging.level.com.example=DEBUG

    # Application properties
    app.message=hello gke
    app.version=1.0.0
    app.environment=gke
    app.gke.message=*****This message is from GKE (message is from configmap) *****

    # Actuator properties
    management.endpoints.web.exposure.include=health,info
    management.endpoint.health.show-details=always
    management.health.probes.enabled=true
    server.tomcat.threads.max=200
    server.tomcat.threads.min-spare=10
